services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    platform: linux/amd64
    volumes:
      - ${SOURCE_DIR:-./}:/app
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-debug}"
      XDEBUG_CONFIG: "${XDEBUG_CONFIG:-client_host=host.docker.internal start_with_request=trigger idekey=PHPSTORM output_dir=/app/build/xdebug}"
    extra_hosts:
      - host.docker.internal:host-gateway
