name: Code Quality
on: [push, pull_request]
jobs:
  ci:
    name: PHP ${{ matrix.php }}
    strategy:
      matrix:
        php: [ '8.3', '8.4' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: int-to-uuid-integration:${{ matrix.php }}
          build-args: PHP_VERSION=${{ matrix.php }}
          load: true
          pull: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: docker run --rm int-to-uuid-integration:${{ matrix.php }} composer run-script ci
